from Tkinter import*
pencere = Tk()
pencere.geometry("470x600+600+0")
menu = Menu(pencere)
pencere.config(menu=menu)
dosya = Menu(menu, tearoff=0)
menu.add_cascade(label="Dosya",menu=dosya)
dosya.add_command(label="Ac")
dosya.add_command(label="Kaydet")
dosya.add_command(label="Farkli Kaydet...")
dosya.add_command(label="ckis",command=pencere.quit)
yeni = Menu(dosya,tearoff=0)
dosya.add_cascade(label="Yeni",menu=yeni)
yeni.add_command(label="Metin Belgesi")
yeni.add_command(label="Resim Dosyasi")
yeni.add_command(label="pdf")
mainloop()
